"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""



# 20231205 감용록 temlplates를 밖으로 빼서 절대경로 설정
# pathlib 모듈 사용(객체지향)
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent 
TEMPLATE_DIR = BASE_DIR / 'Templates'
STATIC_DIR = BASE_DIR / 'static'
print("@"*100)
print("시스템 실행 : settomgs.py 절대경로 확인")

# os 모듈 사용했을 때
# import os
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) 
# TEMPLATE_DIR = os.path.join(BASE_DIR,'Templates')
# STATIC_DIR=os.path.join(BASE_DIR,'static')
# MEDIA_ROOT=os.path.join(BASE_DIR,'static')

print("- BASE_DIR : ",BASE_DIR)
print("- TEMPLATE_DIR : ",TEMPLATE_DIR)
print("- STATIC_DIR : ",STATIC_DIR)
print("@"*100)
 




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7iioty)5+u%ia(al6*0dp5r4c#7d!we9^v(q53tr0$6d)h&oyy'

# 2306161719 김용록 True일 시, 404 에러 등, 표시하게 된다.
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 2306161709 김용록 장고 실행 시, myapp 디렉토리를 못 잡아서 추가
    'myapp',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'myapp.urls'
    # 시작 URL

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR], # 20231205 김용록 절대경로 설정
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 20231118 김용록 DB연결하기
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysql',
        'USER': 'root',
        'PASSWORD': '20165270',
        'HOST': 'localhost',   # 또는 MySQL 서버의 IP 주소
        'PORT': '3306',        # MySQL의 기본 포트 번호
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 202312061554 김용록 css 사용을 위해 static 정의
STATIC_URL = 'static/'
STATICFILES_DIRS=[
    STATIC_DIR,
]
# LOGIN_REDIRECT_URL='/afterlogin'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
